### ISSUE TITLE
Request for VSC recipe

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/lbt-recipes#396]
hi @chriswmackey ,
have you/we planned to implement the Vertical Sky Component recipe at some point? 

With kind regards,
Olivier

**Comment by chriswmackey** [comment]
Hey @DambronOlivier ,

Sorry for the late response. You asked this question at the right time as I just added a recipe for it a week or two ago.  However, it's called `sky-view` instead of `vertical-sky-component`  since VSC is really just a Sky View study run with specific criteria (cloudy sky and vertically-oriented geometry).

You see that I explain this in [the repo that houses the specific recipe code](https://github.com/pollination/sky-view) and in [the description of the LBT Grasshopper component](https://github.com/ladybug-tools/honeybee-grasshopper-radiance/blob/master/honeybee_grasshopper_radiance/src/HB%20Sky%20View.py#L11-L24).

Enjoy!
